// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxSgetytrD_qIbeAY7bhaebT30WMjCWik',
    appId: '1:17741994482:web:1d864936d1dbb5a86cb36b',
    messagingSenderId: '17741994482',
    projectId: 'cake-mamma-13154',
    authDomain: 'cake-mamma-13154.firebaseapp.com',
    storageBucket: 'cake-mamma-13154.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRPiTzOEKPzdstTjzAR0fr29MswRqREI',
    appId: '1:17741994482:android:5678429f90d01aec6cb36b',
    messagingSenderId: '17741994482',
    projectId: 'cake-mamma-13154',
    storageBucket: 'cake-mamma-13154.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxSgetytrD_qIbeAY7bhaebT30WMjCWik',
    appId: '1:17741994482:web:d23d61f21fca73426cb36b',
    messagingSenderId: '17741994482',
    projectId: 'cake-mamma-13154',
    authDomain: 'cake-mamma-13154.firebaseapp.com',
    storageBucket: 'cake-mamma-13154.firebasestorage.app',
  );

}
